### ISSUE TITLE
Custom Commands: %uid% and %dbid% has the same result

### ISSUE THREAD

**Issue by DaweDie** [irgendwr/sinusbot-scripts#3]
Whenever i uses %uid% and %dbid% placeholders, they will have the same results which is databaseID(?I am not sure about this?)/userID. 
![Screenshot_9](https://user-images.githubusercontent.com/47169312/54560378-88da4600-49c2-11e9-8001-a3489dbdac0f.png)
![Screenshot_10](https://user-images.githubusercontent.com/47169312/54560379-88da4600-49c2-11e9-85fa-0051eab03fc9.png)

**Comment by irgendwr** [comment]
From the context I'm assuming that you're using the script on discord:
Discord clients *only have a uid*, there is no "database ID" (dbid) that's from TeamSpeak.
And the ID's that you get are not just the user ID on discord but instead: `<guild id>/<user id>`

The placeholders are there because teamspeak clients have three different IDs: id (temporary), uid (unique ID) and dbid (database ID).
On discord there is only the user ID, that's why they all print the same thing as explained above.

Sooo yeah... that makes sense and is not a bug 😃

**Comment by DaweDie** [comment]
Oh, I see, but than how can i mention a member with the %uid%? Is there any way to get the user ID, without the guild ID? I've tried to put it into a <@ > tag, but it just prints the numbers. (Like <@6336628/75497975>)

**Comment by irgendwr** [comment]
So you need a "mention" placeholder? I could do that probably.

**Comment by DaweDie** [comment]
Yes, that would be great.

**Comment by irgendwr** [comment]
added in 5821dd3, https://raw.githubusercontent.com/irgendwr/sinusbot-scripts/master/custom_commands.js (not tested but should work)

**Comment by DaweDie** [comment]
It works. Thank you mate.
